include:
  - board: xiao_ble
    shield: totem
  - board: xiao_ble
    shield: totem_left
  - board: xiao_ble
    shield: totem_right
  - board: xiao_ble
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
# there is no settingsreset (needed) for the XIAO
